application: yardvote
version: 1
runtime: python
api_version: 1

handlers:
- url: /stylesheets
  static_dir: public/stylesheets

- url: /javascripts
  static_dir: public/javascripts

- url: /images
  static_dir: public/images

- url: /.*
  script: yardvote.py